EXERCISE_IMAGE_MAP = {
    "Default": "exercisepic/profile_default.png",
    "Push-Up": "exercisepic/push up.jpg",
    "Squats": "exercisepic/squat.jpeg",
    "Wall Sit": "exercisepic/Wall Sit.jpeg",
    "Standing Knee Raise": "exercisepic/Standing Knee Raise.jpeg",
    "Plank": "exercisepic/Plank.jpeg",
    "Step-Up": "exercisepic/Step-Up.jpeg",
    "Single Leg Glute Bridge": "exercisepic/Single Leg Glute Bridge.jpg",
    "Reverse Lunge": "exercisepic/Reverse Lunge.jpg",
    "Decline Push Up": "exercisepic/Decline Push Up.jpg",
    "Diamond Push Up": "exercisepic/Diamond PushUp.png",
    "Flutter Kicks": "exercisepic/Flutter Kicks.jpg",
    "Forward Fold": "exercisepic/Forward Fold.jpg",
    "Frog Pump": "exercisepic/Frog Pump.png",
    "Glute Bridge": "exercisepic/Glute Bridge.jpg",
    "Heel Touch": "exercisepic/Heel Touch.jpg",
    "Hip Flexor Stretch": "exercisepic/Hip Flexor Stretch.jpg",
    "Hip Hinge": "exercisepic/Hip Hinge.jpg",
    "Hip Thrust": "exercisepic/Hip Thrust.jpg",
    "Hollow Hold": "exercisepic/Hollow Hold.png",
    "Leg Raise": "exercisepic/Leg Raise.jpg",
    "Light Hops": "exercisepic/Light Hops.jpg",
    "March in Place": "exercisepic/March in Place.png",
    "Pike Push Up": "exercisepic/Pike Push Up.jpg",
    "Punches": "exercisepic/Punches.jpg",
    "Seated March": "exercisepic/Seated March.png",
    "Shoulder Mobility Circle": "exercisepic/Shoulder Mobility Circle.jpg",
    "Side Leg Lift": "exercisepic/Side Leg Lift.jpg",
    "Side Lunge": "exercisepic/Side Lunge.png",
    "Side Plank Raise": "exercisepic/Side Plank Raise.jpg",
    "Sit Ups": "exercisepic/Sit Ups.jpg",
    "Squat Jumps": "exercisepic/Squat Jumps.jpg",
    "Standing Crunch": "exercisepic/Standing Crunch.jpg",
    "Standing Torso Twist": "exercisepic/Standing Torso Twist.jpg",
    "Standing Twist": "exercisepic/Standing Twist.png",
    "Superman Hold": "exercisepic/Superman Hold.png",
    "Tricep Dip": "exercisepic/Tricep Dip.jpg",
    "Wall Push Up": "exercisepic/Wall Push Up.png",
    "Wide Push Up": "exercisepic/Wide Push Up.jpg",
    "Arm Circles": "exercisepic/Arm Circles.png",
    "Back Stretch": "exercisepic/Back Stretch.jpg",
    "Bicycle Crunch": "exercisepic/Bicycle Crunch.jpg",
    "Bird Dog": "exercisepic/Bird Dog.jpg",
    "Bridge March": "exercisepic/Bridge march.jpg",
    "Bulgarian Split Squat": "exercisepic/Bulgarian Split Squat.jpg",
    "Burpees": "exercisepic/Burpees.png",
    "Curl Ups": "exercisepic/Curl Ups.jpg",
    "adasd": "exercisepic/default.png",
    "dsada": "exercisepic/default.png",
    "hi": "C:\Users\Ellise James Tamayo\PycharmProjects\SystemInteg-FitnessGo\exercisepic\Butt Kicks.jpg",
}
